<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generated by Codia AI</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600&display=swap" />
    <style>
        :root {
  --default-font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
    Ubuntu, "Helvetica Neue", Helvetica, Arial, "PingFang SC",
    "Hiragino Sans GB", "Microsoft Yahei UI", "Microsoft Yahei",
    "Source Han Sans CN", sans-serif;
}

.main-container {
  overflow: hidden;
}

.main-container,
.main-container * {
  box-sizing: border-box;
}

input,
select,
textarea,
button {
  outline: 0;
}

.main-container {
  position: relative;
  width: 595px;
  height: 841px;
  margin: 0 auto;
  background: rgba(0, 0, 0, 0);
  overflow: hidden;
}
.root {
  position: absolute;
  height: 841px;
  top: 0;
  right: 0;
  left: 0;
  background: rgba(0, 0, 0, 0);
}
.groups {
  position: absolute;
  width: 595px;
  height: 841px;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0);
  z-index: 1;
}
.image {
  position: relative;
  width: 581px;
  height: 3px;
  margin: 0 0 0 14px;
  background: url(./assets/images/14d579b42696575973d7e2e2247dc176f1779d1c.png)
    no-repeat center;
  background-size: cover;
  z-index: 143;
}
.flex-row-b {
  position: absolute;
  width: 595px;
  height: 828px;
  right: 0;
  bottom: 0;
  z-index: 140;
}
.image-1 {
  position: absolute;
  width: 4px;
  height: 828px;
  right: 0;
  bottom: 0;
  background: url(./assets/images/f2f0ba3f36108e9b9461375e39783b8976f93210.png)
    no-repeat center;
  background-size: cover;
  z-index: 41;
}
.background {
  position: absolute;
  width: 2px;
  height: 23px;
  right: 52px;
  bottom: 797px;
  background: url(./assets/images/6a304392b3b2478a7d12b3dc97c1037b4e4ddf24.png)
    no-repeat center;
  background-size: cover;
  z-index: 136;
}
.mashreq {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 14px;
  right: 144px;
  bottom: 802px;
  color: #c3c5c4;
  font-family: Inter, var(--default-font-family);
  font-size: 10.199999809265137px;
  font-weight: 600;
  line-height: 12.344px;
  text-align: left;
  white-space: nowrap;
  z-index: 140;
}
.al-mashreq {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 16px;
  right: 64px;
  bottom: 800px;
  color: #cacccb;
  font-family: Inter, var(--default-font-family);
  font-size: 12.300000190734863px;
  font-weight: 600;
  line-height: 14.886px;
  text-align: left;
  white-space: nowrap;
  z-index: 137;
}
.image-2 {
  position: absolute;
  width: 28px;
  height: 14px;
  right: 113px;
  bottom: 801px;
  background: url(./assets/images/cf4830f6f352f89304078fb6dedd3ba71cce5b5a.png)
    no-repeat center;
  background-size: cover;
  z-index: 139;
}
.ned {
  display: flex;
  align-items: center;
  justify-content: center;
  position: absolute;
  width: 14px;
  height: 10px;
  right: 29px;
  bottom: 805px;
  color: #e1e1e1;
  font-family: Inter, var(--default-font-family);
  font-size: 5.900000095367432px;
  font-weight: 600;
  line-height: 7.14px;
  text-align: center;
  white-space: nowrap;
  z-index: 135;
}
.aldlam {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 9px;
  right: 113px;
  bottom: 791px;
  color: #dddddd;
  font-family: Inter, var(--default-font-family);
  font-size: 5px;
  font-weight: 600;
  line-height: 6.051px;
  text-align: left;
  white-space: nowrap;
  z-index: 138;
}
.groups-3 {
  position: absolute;
  width: 595px;
  height: 250px;
  right: 0;
  bottom: 537px;
  font-size: 0px;
  background: rgba(0, 0, 0, 0);
  z-index: 93;
}
.kashf-hisab-al-jari {
  display: block;
  position: relative;
  height: 11px;
  margin: 9px 0 0 488px;
  color: #a7abaa;
  font-family: Inter, var(--default-font-family);
  font-size: 6.699999809265137px;
  font-weight: 600;
  line-height: 8.109px;
  text-align: left;
  white-space: nowrap;
  z-index: 132;
}
.current-account-statement {
  display: block;
  position: relative;
  height: 12px;
  margin: -9px 0 0 292px;
  color: #9ea3a2;
  font-family: Inter, var(--default-font-family);
  font-size: 9px;
  font-weight: 600;
  line-height: 10.892px;
  text-align: left;
  white-space: nowrap;
  z-index: 133;
}
.islamic-banking {
  display: block;
  position: relative;
  height: 11px;
  margin: -10px 0 0 25px;
  color: #808080;
  font-family: Inter, var(--default-font-family);
  font-size: 7.300000190734863px;
  font-weight: 600;
  line-height: 8.835px;
  text-align: left;
  white-space: nowrap;
  z-index: 134;
}
.background-4 {
  position: relative;
  width: 280px;
  height: 1px;
  margin: 2px 0 0 289px;
  background: url(./assets/images/60df8a7d5735a0d63702daecb6d31f6595d06db2.png)
    no-repeat center;
  background-size: cover;
  z-index: 131;
}
.raqm-al-hisab {
  display: block;
  position: relative;
  height: 10px;
  margin: 0 0 0 505px;
  color: #c2c4c4;
  font-family: Inter, var(--default-font-family);
  font-size: 7.300000190734863px;
  font-weight: 600;
  line-height: 8.835px;
  text-align: left;
  white-space: nowrap;
  z-index: 126;
}
.flex-row-d {
  display: flex;
  align-items: center;
  justify-content: space-between;
  position: relative;
  width: 99px;
  height: 11px;
  margin: -9px 0 0 372px;
  z-index: 128;
}
.account-number {
  flex-shrink: 0;
  position: relative;
  height: 11px;
  color: #7b7f7d;
  font-family: Inter, var(--default-font-family);
  font-size: 7.900000095367432px;
  font-weight: 600;
  line-height: 11px;
  text-align: left;
  white-space: nowrap;
  z-index: 128;
}
.aed {
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
  position: relative;
  width: 18px;
  height: 10px;
  color: #777a79;
  font-family: Inter, var(--default-font-family);
  font-size: 8px;
  font-weight: 600;
  line-height: 10px;
  text-align: center;
  white-space: nowrap;
  z-index: 127;
}
.account-number-5 {
  display: block;
  position: relative;
  height: 11px;
  margin: -10px 0 0 292px;
  color: #b5b8b7;
  font-family: Inter, var(--default-font-family);
  font-size: 8.199999809265137px;
  font-weight: 600;
  line-height: 9.924px;
  text-align: left;
  white-space: nowrap;
  z-index: 129;
}
.manoj-pudasaini {
  display: block;
  position: relative;
  height: 11px;
  margin: -8px 0 0 25px;
  color: #838383;
  font-family: Inter, var(--default-font-family);
  font-size: 7.900000095367432px;
  font-weight: 600;
  line-height: 9.561px;
  text-align: left;
  white-space: nowrap;
  z-index: 130;
}
.background-6 {
  position: relative;
  width: 280px;
  height: 1px;
  margin: 0 0 0 289px;
  background: url(./assets/images/b87ff2d6acc79f7b66b2b4384736e0a644923245.png)
    no-repeat center;
  background-size: cover;
  z-index: 125;
}
.aban {
  display: flex;
  align-items: center;
  justify-content: center;
  position: relative;
  width: 17px;
  height: 9px;
  margin: 0 0 0 539px;
  color: #c4c6c6;
  font-family: Inter, var(--default-font-family);
  font-size: 8.5px;
  font-weight: 600;
  line-height: 9px;
  text-align: center;
  white-space: nowrap;
  z-index: 121;
}
.flex-row-abb {
  display: flex;
  align-items: center;
  justify-content: space-between;
  position: relative;
  width: 197px;
  height: 10px;
  margin: -7px 0 0 292px;
  z-index: 123;
}
.iban {
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
  position: relative;
  width: 22px;
  height: 10px;
  color: #aaaeac;
  font-family: Inter, var(--default-font-family);
  font-size: 8.5px;
  font-weight: 600;
  line-height: 10px;
  text-align: center;
  white-space: nowrap;
  z-index: 123;
}
.ae {
  flex-shrink: 0;
  position: relative;
  height: 10px;
  color: #7c807f;
  font-family: Inter, var(--default-font-family);
  font-size: 7.900000095367432px;
  font-weight: 600;
  line-height: 10px;
  text-align: left;
  white-space: nowrap;
  z-index: 122;
}
.flex-row {
  position: relative;
  width: 480px;
  height: 12px;
  margin: -7px 0 0 25px;
  z-index: 124;
}
.alkuwait-street {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 12px;
  right: 289px;
  bottom: 0;
  color: #858585;
  font-family: Inter, var(--default-font-family);
  font-size: 7.800000190734863px;
  font-weight: 600;
  line-height: 9.44px;
  text-align: left;
  white-space: nowrap;
  z-index: 124;
}
.background-7 {
  position: absolute;
  width: 215px;
  height: 1px;
  right: 0;
  bottom: 1px;
  background: url(./assets/images/728307020bedbf996c01d7cbbcb1c3fe98fdf2ed.png)
    no-repeat center;
  background-size: cover;
  z-index: 120;
}
.rafm-taresh-al-amel {
  display: block;
  position: relative;
  height: 10px;
  margin: -2px 0 0 505px;
  color: #bbbdbd;
  font-family: Inter, var(--default-font-family);
  font-size: 6.599999904632568px;
  font-weight: 600;
  line-height: 7.987px;
  text-align: left;
  white-space: nowrap;
  z-index: 116;
}
.customer {
  display: block;
  position: relative;
  height: 9px;
  margin: -8px 0 0 292px;
  color: #bdbfbf;
  font-family: Inter, var(--default-font-family);
  font-size: 7.300000190734863px;
  font-weight: 600;
  line-height: 8.835px;
  text-align: left;
  white-space: nowrap;
  z-index: 118;
}
.phone-number {
  display: block;
  position: relative;
  height: 10px;
  margin: -8px 0 0 389px;
  color: #7f8484;
  font-family: Inter, var(--default-font-family);
  font-size: 7.900000095367432px;
  font-weight: 600;
  line-height: 9.561px;
  text-align: left;
  white-space: nowrap;
  z-index: 117;
}
.address {
  display: block;
  position: relative;
  height: 11px;
  margin: -9px 0 0 25px;
  color: #868686;
  font-family: Inter, var(--default-font-family);
  font-size: 6.400000095367432px;
  font-weight: 600;
  line-height: 7.745px;
  text-align: left;
  white-space: nowrap;
  z-index: 119;
}
.background-8 {
  position: relative;
  width: 283px;
  height: 3px;
  margin: -1px 0 0 288px;
  background: url(./assets/images/f1a526fe8c22ac809747795194d1a492f5d030a1.png)
    no-repeat center;
  background-size: cover;
  z-index: 115;
}
.flex-row-eb {
  display: flex;
  align-items: center;
  justify-content: space-between;
  position: relative;
  width: 481px;
  height: 11px;
  margin: 1px 0 0 25px;
  z-index: 114;
}
.location {
  flex-shrink: 0;
  position: relative;
  height: 11px;
  color: #808080;
  font-family: Inter, var(--default-font-family);
  font-size: 8px;
  font-weight: 600;
  line-height: 11px;
  text-align: left;
  white-space: nowrap;
  z-index: 114;
}
.image-9 {
  flex-shrink: 0;
  position: relative;
  width: 217px;
  height: 8px;
  background: url(./assets/images/af190ffb759482282f91d75ea78ebf4abca97f87.png)
    no-repeat center;
  background-size: cover;
  z-index: 113;
}
.image-a {
  position: relative;
  width: 224px;
  height: 10px;
  margin: -3px 0 0 347px;
  background: url(./assets/images/30550567c25274ab8eb13ef17cb582cd1346bccf.png)
    no-repeat center;
  background-size: cover;
  z-index: 111;
}
.country-code {
  display: flex;
  align-items: center;
  justify-content: center;
  position: relative;
  width: 14px;
  height: 10px;
  margin: -3px 0 0 25px;
  color: #797979;
  font-family: Inter, var(--default-font-family);
  font-size: 8px;
  font-weight: 600;
  line-height: 9.682px;
  text-align: center;
  white-space: nowrap;
  z-index: 112;
}
.greeting {
  display: block;
  position: relative;
  height: 11px;
  margin: 13px 0 0 26px;
  color: #c2c2c2;
  font-family: Inter, var(--default-font-family);
  font-size: 6.199999809265137px;
  font-weight: 600;
  line-height: 7.503px;
  text-align: left;
  white-space: nowrap;
  z-index: 110;
}
.compliance-message {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: relative;
  width: 548px;
  height: 41px;
  margin: 1px 0 0 26.2px;
  color: #bbbbbb;
  font-family: Inter, var(--default-font-family);
  font-size: 7.199999809265137px;
  font-weight: 600;
  line-height: 12.708px;
  text-align: left;
  text-overflow: initial;
  z-index: 109;
  overflow: hidden;
}
.flex-row-e {
  position: relative;
  width: 214px;
  height: 13px;
  margin: 3px 0 0 26px;
  z-index: 108;
}
.statement-period {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 13px;
  right: 124px;
  bottom: 0;
  color: #bababa;
  font-family: Inter, var(--default-font-family);
  font-size: 8.5px;
  font-weight: 600;
  line-height: 10.287px;
  text-align: left;
  white-space: nowrap;
  z-index: 108;
}
.button {
  position: absolute;
  width: 48px;
  height: 12px;
  right: 0;
  bottom: 0;
  cursor: pointer;
  color: #848484;
  font-family: Inter, var(--default-font-family);
  font-size: 6.400000095367432px;
  font-weight: 600;
  line-height: 7.745px;
  background: transparent;
  border: none;
  z-index: 105;
}
.date {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 11px;
  right: 72px;
  bottom: 0;
  color: #7f7f7f;
  font-family: Inter, var(--default-font-family);
  font-size: 6.400000095367432px;
  font-weight: 600;
  line-height: 7.745px;
  text-align: left;
  white-space: nowrap;
  z-index: 107;
}
.to {
  display: flex;
  align-items: center;
  justify-content: center;
  position: absolute;
  width: 11px;
  height: 9px;
  right: 55px;
  bottom: 1px;
  color: #b1b1b1;
  font-family: Inter, var(--default-font-family);
  font-size: 8px;
  font-weight: 600;
  line-height: 9px;
  text-align: center;
  white-space: nowrap;
  z-index: 106;
}
.background-b {
  position: relative;
  width: 544px;
  height: 1px;
  margin: 61px 0 0 24px;
  background: #ffffff;
  z-index: 94;
}
.flex-row-e-c {
  position: absolute;
  width: 532px;
  height: 23px;
  right: 36px;
  bottom: 8px;
  z-index: 104;
}
.debit {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 12px;
  right: 147px;
  bottom: 11px;
  color: #b2b2b2;
  font-family: Inter, var(--default-font-family);
  font-size: 7.900000095367432px;
  font-weight: 600;
  line-height: 9.561px;
  text-align: left;
  white-space: nowrap;
  z-index: 100;
}
.credit {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 11px;
  right: 68px;
  bottom: 12px;
  color: #adadad;
  font-family: Inter, var(--default-font-family);
  font-size: 7.900000095367432px;
  font-weight: 300;
  line-height: 9.561px;
  text-align: left;
  white-space: nowrap;
  z-index: 99;
}
.balance {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 12px;
  right: 0;
  bottom: 11px;
  color: #b4b4b4;
  font-family: Inter, var(--default-font-family);
  font-size: 7.900000095367432px;
  font-weight: 600;
  line-height: 9.561px;
  text-align: left;
  white-space: nowrap;
  z-index: 96;
}
.transaction {
  display: flex;
  align-items: center;
  justify-content: center;
  position: absolute;
  width: 49px;
  height: 20px;
  right: 416.667px;
  bottom: 2px;
  color: #bdbdbd;
  font-family: Inter, var(--default-font-family);
  font-size: 7.800000190734863px;
  font-weight: 600;
  line-height: 9.512px;
  text-align: center;
  text-overflow: initial;
  z-index: 103;
  overflow: hidden;
}
.reference-number {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 11px;
  right: 236px;
  bottom: 11px;
  color: #bbbbbb;
  font-family: Inter, var(--default-font-family);
  font-size: 8.399999618530273px;
  font-weight: 600;
  line-height: 10.166px;
  text-align: left;
  white-space: nowrap;
  z-index: 102;
}
.date-d {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 13px;
  right: 507px;
  bottom: 0;
  color: #bebebe;
  font-family: Inter, var(--default-font-family);
  font-size: 9.5px;
  font-weight: 300;
  line-height: 11.497px;
  text-align: left;
  white-space: nowrap;
  z-index: 104;
}
.amount {
  display: flex;
  align-items: center;
  justify-content: center;
  position: absolute;
  width: 17px;
  height: 11px;
  right: 149px;
  bottom: 0;
  color: #bebebe;
  font-family: Inter, var(--default-font-family);
  font-size: 8.699999809265137px;
  font-weight: 600;
  line-height: 10.529px;
  text-align: center;
  white-space: nowrap;
  z-index: 98;
}
.balance-amount {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  width: 28px;
  height: 10px;
  right: 2px;
  bottom: 1px;
  color: #bcbcbc;
  font-family: Inter, var(--default-font-family);
  font-size: 4.199999809265137px;
  font-weight: 600;
  line-height: 5.083px;
  text-align: left;
  z-index: 95;
}
.remaining-balance {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 11px;
  right: 95px;
  bottom: 9px;
  color: #bcbcbc;
  font-family: Inter, var(--default-font-family);
  font-size: 8.800000190734863px;
  font-weight: 600;
  line-height: 10.65px;
  text-align: left;
  white-space: nowrap;
  z-index: 97;
}
.reference-number-e {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 11px;
  right: 270px;
  bottom: 8px;
  color: #bebebe;
  font-family: Inter, var(--default-font-family);
  font-size: 7.699999809265137px;
  font-weight: 600;
  line-height: 9.319px;
  text-align: left;
  white-space: nowrap;
  z-index: 101;
}
.amount-f {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 11px;
  right: 26px;
  bottom: 525px;
  color: #9f9f9f;
  font-family: Inter, var(--default-font-family);
  font-size: 7.199999809265137px;
  font-weight: 600;
  line-height: 8.714px;
  text-align: left;
  white-space: nowrap;
  z-index: 91;
}
.opening-balance {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 11px;
  right: 448px;
  bottom: 524px;
  color: #9c9c9c;
  font-family: Inter, var(--default-font-family);
  font-size: 7.199999809265137px;
  font-weight: 600;
  line-height: 8.714px;
  text-align: left;
  white-space: nowrap;
  z-index: 92;
}
.background-10 {
  position: absolute;
  width: 545px;
  height: 1px;
  right: 25px;
  bottom: 228px;
  background: #efefef;
  z-index: 40;
}
.transaction-details {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 10px;
  right: 362px;
  bottom: 217px;
  color: #b4b4b4;
  font-family: Inter, var(--default-font-family);
  font-size: 7.900000095367432px;
  font-weight: 600;
  line-height: 9.561px;
  text-align: left;
  white-space: nowrap;
  z-index: 38;
}
.span {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 12px;
  right: 26px;
  bottom: 214px;
  color: #a7a7a7;
  font-family: Inter, var(--default-font-family);
  font-size: 7.400000095367432px;
  font-weight: 600;
  line-height: 8.956px;
  text-align: left;
  white-space: nowrap;
  z-index: 34;
}
.span-11 {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  width: 47px;
  height: 12px;
  right: 522px;
  bottom: 213px;
  color: #979797;
  font-family: Inter, var(--default-font-family);
  font-size: 6.400000095367432px;
  font-weight: 600;
  line-height: 7.745px;
  text-align: left;
  z-index: 39;
}
.span-12 {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 11px;
  right: 261px;
  bottom: 214px;
  color: #ababab;
  font-family: Inter, var(--default-font-family);
  font-size: 7.300000190734863px;
  font-weight: 600;
  line-height: 8.835px;
  text-align: left;
  white-space: nowrap;
  z-index: 36;
}
.span-13 {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 11px;
  right: 184px;
  bottom: 214px;
  color: #9f9f9f;
  font-family: Inter, var(--default-font-family);
  font-size: 7.900000095367432px;
  font-weight: 600;
  line-height: 9.561px;
  text-align: left;
  white-space: nowrap;
  z-index: 35;
}
.div {
  position: absolute;
  width: 546px;
  height: 1px;
  right: 25px;
  bottom: 189px;
  background: #eaeaea;
  z-index: 33;
}
.span-14 {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 10px;
  right: 354px;
  bottom: 178px;
  color: #a5a5a5;
  font-family: Inter, var(--default-font-family);
  font-size: 7.300000190734863px;
  font-weight: 600;
  line-height: 8.835px;
  text-align: left;
  white-space: nowrap;
  z-index: 31;
}
.span-15 {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 11px;
  right: 25px;
  bottom: 176px;
  color: #a4a4a4;
  font-family: Inter, var(--default-font-family);
  font-size: 7.800000190734863px;
  font-weight: 600;
  line-height: 9.44px;
  text-align: left;
  white-space: nowrap;
  z-index: 27;
}
.span-16 {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  width: 46px;
  height: 12px;
  right: 523px;
  bottom: 174px;
  color: #9f9f9f;
  font-family: Inter, var(--default-font-family);
  font-size: 6.400000095367432px;
  font-weight: 600;
  line-height: 7.745px;
  text-align: left;
  z-index: 32;
}
.span-17 {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 11px;
  right: 260px;
  bottom: 175px;
  color: #acacac;
  font-family: Inter, var(--default-font-family);
  font-size: 7.800000190734863px;
  font-weight: 600;
  line-height: 9.44px;
  text-align: left;
  white-space: nowrap;
  z-index: 29;
}
.span-18 {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 11px;
  right: 184px;
  bottom: 175px;
  color: #a0a0a0;
  font-family: Inter, var(--default-font-family);
  font-size: 7.300000190734863px;
  font-weight: 600;
  line-height: 8.835px;
  text-align: left;
  white-space: nowrap;
  z-index: 28;
}
.span-19 {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 11px;
  right: 386px;
  bottom: 166px;
  color: #9f9f9f;
  font-family: Inter, var(--default-font-family);
  font-size: 6.400000095367432px;
  font-weight: 600;
  line-height: 7.745px;
  text-align: left;
  white-space: nowrap;
  z-index: 30;
}
.div-1a {
  position: absolute;
  width: 545px;
  height: 1px;
  right: 26px;
  bottom: 163px;
  background: #e4e4e4;
  z-index: 26;
}
.span-1b {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 10px;
  right: 352px;
  bottom: 152px;
  color: #a3a3a3;
  font-family: Inter, var(--default-font-family);
  font-size: 7.900000095367432px;
  font-weight: 600;
  line-height: 9.561px;
  text-align: left;
  white-space: nowrap;
  z-index: 16;
}
.span-1c {
  display: flex;
  align-items: center;
  justify-content: center;
  position: absolute;
  width: 23px;
  height: 12px;
  right: 185px;
  bottom: 149px;
  color: #9c9c9c;
  font-family: Inter, var(--default-font-family);
  font-size: 7.300000190734863px;
  font-weight: 600;
  line-height: 8.835px;
  text-align: center;
  white-space: nowrap;
  z-index: 13;
}
.span-1d {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 10px;
  right: 25px;
  bottom: 151px;
  color: #a3a3a3;
  font-family: Inter, var(--default-font-family);
  font-size: 7.900000095367432px;
  font-weight: 600;
  line-height: 9.561px;
  text-align: left;
  white-space: nowrap;
  z-index: 25;
}
.span-1e {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 11px;
  right: 522px;
  bottom: 149px;
  color: #9e9e9e;
  font-family: Inter, var(--default-font-family);
  font-size: 6.400000095367432px;
  font-weight: 600;
  line-height: 7.745px;
  text-align: left;
  white-space: nowrap;
  z-index: 17;
}
.span-1f {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 11px;
  right: 260px;
  bottom: 149px;
  color: #aaaaaa;
  font-family: Inter, var(--default-font-family);
  font-size: 7.300000190734863px;
  font-weight: 600;
  line-height: 8.835px;
  text-align: left;
  white-space: nowrap;
  z-index: 14;
}
.span-20 {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 12px;
  right: 397px;
  bottom: 139px;
  color: #a9a9a9;
  font-family: Inter, var(--default-font-family);
  font-size: 7.199999809265137px;
  font-weight: 600;
  line-height: 8.714px;
  text-align: left;
  white-space: nowrap;
  z-index: 15;
}
.span-21 {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 11px;
  right: 361px;
  bottom: 126px;
  color: #a5a5a5;
  font-family: Inter, var(--default-font-family);
  font-size: 7.900000095367432px;
  font-weight: 600;
  line-height: 9.561px;
  text-align: left;
  white-space: nowrap;
  z-index: 11;
}
.span-22 {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 12px;
  right: 184px;
  bottom: 123px;
  color: #9d9d9d;
  font-family: Inter, var(--default-font-family);
  font-size: 7.900000095367432px;
  font-weight: 600;
  line-height: 9.561px;
  text-align: left;
  white-space: nowrap;
  z-index: 8;
}
.span-23 {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 12px;
  right: 522px;
  bottom: 122px;
  color: #9e9e9e;
  font-family: Inter, var(--default-font-family);
  font-size: 7.300000190734863px;
  font-weight: 600;
  line-height: 8.835px;
  text-align: left;
  white-space: nowrap;
  z-index: 12;
}
.span-24 {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 11px;
  right: 260px;
  bottom: 123px;
  color: #acacac;
  font-family: Inter, var(--default-font-family);
  font-size: 7.300000190734863px;
  font-weight: 600;
  line-height: 8.835px;
  text-align: left;
  white-space: nowrap;
  z-index: 9;
}
.span-25 {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 11px;
  right: 371px;
  bottom: 114px;
  color: #9e9e9e;
  font-family: Inter, var(--default-font-family);
  font-size: 6.400000095367432px;
  font-weight: 600;
  line-height: 7.745px;
  text-align: left;
  white-space: nowrap;
  z-index: 10;
}
.div-26 {
  position: absolute;
  width: 416px;
  height: 1px;
  right: 155px;
  bottom: 111px;
  background: #cdcdcd;
  z-index: 23;
}
.span-27 {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 12px;
  right: 362px;
  bottom: 99px;
  color: #b6b6b6;
  font-family: Inter, var(--default-font-family);
  font-size: 7.800000190734863px;
  font-weight: 600;
  line-height: 9.44px;
  text-align: left;
  white-space: nowrap;
  z-index: 6;
}
.span-28 {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 12px;
  right: 522px;
  bottom: 96px;
  color: #a4a4a4;
  font-family: Inter, var(--default-font-family);
  font-size: 7.300000190734863px;
  font-weight: 600;
  line-height: 8.835px;
  text-align: left;
  white-space: nowrap;
  z-index: 7;
}
.span-29 {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 11px;
  right: 262px;
  bottom: 97px;
  color: #aeaeae;
  font-family: Inter, var(--default-font-family);
  font-size: 7.300000190734863px;
  font-weight: 600;
  line-height: 8.835px;
  text-align: left;
  white-space: nowrap;
  z-index: 4;
}
.span-2a {
  display: flex;
  align-items: center;
  justify-content: center;
  position: absolute;
  width: 23px;
  height: 11px;
  right: 185px;
  bottom: 97px;
  color: #a0a0a0;
  font-family: Inter, var(--default-font-family);
  font-size: 7.300000190734863px;
  font-weight: 600;
  line-height: 8.835px;
  text-align: center;
  white-space: nowrap;
  z-index: 3;
}
.span-2b {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 12px;
  right: 371px;
  bottom: 87px;
  color: #b1b1b1;
  font-family: Inter, var(--default-font-family);
  font-size: 7.800000190734863px;
  font-weight: 600;
  line-height: 9.44px;
  text-align: left;
  white-space: nowrap;
  z-index: 5;
}
.div-2c {
  position: absolute;
  width: 595px;
  height: 79px;
  right: 0;
  bottom: 442px;
  background: rgba(0, 0, 0, 0);
  z-index: 79;
}
.div-2d {
  position: relative;
  width: 544px;
  height: 1px;
  margin: 2px 0 0 24px;
  background: #d2d2d2;
  z-index: 90;
}
.span-2e {
  display: block;
  position: relative;
  height: 10px;
  margin: 1px 0 0 85px;
  color: #afafaf;
  font-family: Inter, var(--default-font-family);
  font-size: 7.800000190734863px;
  font-weight: 600;
  line-height: 9.44px;
  text-align: left;
  white-space: nowrap;
  z-index: 88;
}
.flex-row-a {
  position: relative;
  width: 543px;
  height: 13px;
  margin: -9px 0 0 26px;
  z-index: 89;
}
.span-2f {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 12px;
  right: 0;
  bottom: 1px;
  color: #a3a3a3;
  font-family: Inter, var(--default-font-family);
  font-size: 7.199999809265137px;
  font-weight: 600;
  line-height: 8.714px;
  text-align: left;
  white-space: nowrap;
  z-index: 84;
}
.span-30 {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 11px;
  right: 495px;
  bottom: 1px;
  color: #acacac;
  font-family: Inter, var(--default-font-family);
  font-size: 7.199999809265137px;
  font-weight: 600;
  line-height: 8.714px;
  text-align: left;
  white-space: nowrap;
  z-index: 89;
}
.span-dblc {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 12px;
  right: 235px;
  bottom: 0;
  color: #afafaf;
  font-family: Inter, var(--default-font-family);
  font-size: 7.800000190734863px;
  font-weight: 600;
  line-height: 9.44px;
  text-align: left;
  white-space: nowrap;
  z-index: 86;
}
.span-31 {
  display: flex;
  align-items: center;
  justify-content: center;
  position: absolute;
  width: 19px;
  height: 11px;
  right: 159px;
  bottom: 1px;
  color: #9f9f9f;
  font-family: Inter, var(--default-font-family);
  font-size: 7.900000095367432px;
  font-weight: 600;
  line-height: 9.561px;
  text-align: center;
  white-space: nowrap;
  z-index: 85;
}
.span-32 {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: relative;
  width: 162px;
  height: 12px;
  margin: -3px 0 0 85px;
  color: #989898;
  font-family: Inter, var(--default-font-family);
  font-size: 6.400000095367432px;
  font-weight: 600;
  line-height: 7.745px;
  text-align: left;
  z-index: 87;
}
.mobile-banking {
  display: block;
  position: relative;
  height: 11px;
  margin: 1px 0 0 85px;
  color: #979797;
  font-family: Inter, var(--default-font-family);
  font-size: 6.800000190734863px;
  font-weight: 600;
  line-height: 8.23px;
  text-align: left;
  white-space: nowrap;
  z-index: 83;
}
.span-ae {
  display: block;
  position: relative;
  height: 12px;
  margin: 2px 0 0 85px;
  color: #adadad;
  font-family: Inter, var(--default-font-family);
  font-size: 7.800000190734863px;
  font-weight: 600;
  line-height: 9.44px;
  text-align: left;
  white-space: nowrap;
  z-index: 82;
}
.span-33 {
  display: block;
  position: relative;
  height: 11px;
  margin: 1px 0 0 85px;
  color: #aeaeae;
  font-family: Inter, var(--default-font-family);
  font-size: 7.199999809265137px;
  font-weight: 600;
  line-height: 8.714px;
  text-align: left;
  white-space: nowrap;
  z-index: 81;
}
.mlc {
  display: block;
  position: relative;
  height: 11px;
  margin: 1px 0 0 85px;
  color: #9d9d9d;
  font-family: Inter, var(--default-font-family);
  font-size: 6.400000095367432px;
  font-weight: 600;
  line-height: 7.745px;
  text-align: left;
  white-space: nowrap;
  z-index: 80;
}
.groups-34 {
  position: absolute;
  width: 595px;
  height: 76px;
  right: 0;
  bottom: 366px;
  background: rgba(0, 0, 0, 0);
  z-index: 67;
}
.background-35 {
  position: relative;
  width: 544px;
  height: 1px;
  margin: 0 0 0 24px;
  background: #e5e5e5;
  z-index: 78;
}
.online-local-fund {
  display: block;
  position: relative;
  height: 11px;
  margin: 1px 0 0 86px;
  color: #b3b3b3;
  font-family: Inter, var(--default-font-family);
  font-size: 7.199999809265137px;
  font-weight: 600;
  line-height: 8.714px;
  text-align: left;
  white-space: nowrap;
  z-index: 76;
}
.flex-row-eb-36 {
  position: relative;
  width: 543px;
  height: 13px;
  margin: -10px 0 0 26px;
  z-index: 77;
}
.span-37 {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 12px;
  right: 0;
  bottom: 1px;
  color: #a8a8a8;
  font-family: Inter, var(--default-font-family);
  font-size: 7.300000190734863px;
  font-weight: 600;
  line-height: 8.835px;
  text-align: left;
  white-space: nowrap;
  z-index: 72;
}
.span-38 {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  width: 48px;
  height: 12px;
  right: 495px;
  bottom: 0;
  color: #9e9e9e;
  font-family: Inter, var(--default-font-family);
  font-size: 6.400000095367432px;
  font-weight: 600;
  line-height: 7.745px;
  text-align: left;
  z-index: 77;
}
.span-dblc-39 {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 12px;
  right: 235px;
  bottom: 0;
  color: #acacac;
  font-family: Inter, var(--default-font-family);
  font-size: 7.199999809265137px;
  font-weight: 600;
  line-height: 8.714px;
  text-align: left;
  white-space: nowrap;
  z-index: 74;
}
.span-3a {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 11px;
  right: 159px;
  bottom: 1px;
  color: #a5a5a5;
  font-family: Inter, var(--default-font-family);
  font-size: 7.599999904632568px;
  font-weight: 600;
  line-height: 9.198px;
  text-align: left;
  white-space: nowrap;
  z-index: 73;
}
.span-3b {
  display: block;
  position: relative;
  height: 11px;
  margin: -2px 0 0 85px;
  color: #a2a2a2;
  font-family: Inter, var(--default-font-family);
  font-size: 7.300000190734863px;
  font-weight: 600;
  line-height: 8.835px;
  text-align: left;
  white-space: nowrap;
  z-index: 75;
}
.mobile-banking-3c {
  display: block;
  position: relative;
  height: 12px;
  margin: 1px 0 0 86px;
  color: #979797;
  font-family: Inter, var(--default-font-family);
  font-size: 6.800000190734863px;
  font-weight: 600;
  line-height: 8.23px;
  text-align: left;
  white-space: nowrap;
  z-index: 71;
}
.span-ae-3d {
  display: block;
  position: relative;
  height: 11px;
  margin: 1px 0 0 85px;
  color: #ababab;
  font-family: Inter, var(--default-font-family);
  font-size: 7.300000190734863px;
  font-weight: 600;
  line-height: 8.835px;
  text-align: left;
  white-space: nowrap;
  z-index: 70;
}
.span-3e {
  display: block;
  position: relative;
  height: 12px;
  margin: 2px 0 0 86px;
  color: #b1b1b1;
  font-family: Inter, var(--default-font-family);
  font-size: 6.800000190734863px;
  font-weight: 600;
  line-height: 8.23px;
  text-align: left;
  white-space: nowrap;
  z-index: 69;
}
.mlc-3f {
  display: block;
  position: relative;
  height: 10px;
  margin: 1px 0 0 86px;
  color: #9d9d9d;
  font-family: Inter, var(--default-font-family);
  font-size: 7.300000190734863px;
  font-weight: 600;
  line-height: 8.835px;
  text-align: left;
  white-space: nowrap;
  z-index: 68;
}
.groups-40 {
  position: absolute;
  width: 595px;
  height: 77px;
  right: 0;
  bottom: 288px;
  background: rgba(0, 0, 0, 0);
  z-index: 55;
}
.background-41 {
  position: relative;
  width: 543px;
  height: 1px;
  margin: 0 0 0 25px;
  background: #d8d8d8;
  z-index: 66;
}
.funds-transfer-c {
  display: block;
  position: relative;
  height: 11px;
  margin: 1px 0 0 86px;
  color: #aeaeae;
  font-family: Inter, var(--default-font-family);
  font-size: 7.400000095367432px;
  font-weight: 600;
  line-height: 8.956px;
  text-align: left;
  white-space: nowrap;
  z-index: 64;
}
.flex-row-ac {
  position: relative;
  width: 543px;
  height: 13px;
  margin: -10px 0 0 26px;
  z-index: 65;
}
.span-42 {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 12px;
  right: 0;
  bottom: 1px;
  color: #a3a3a3;
  font-family: Inter, var(--default-font-family);
  font-size: 7.400000095367432px;
  font-weight: 600;
  line-height: 8.956px;
  text-align: left;
  white-space: nowrap;
  z-index: 60;
}
.span-43 {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  width: 49px;
  height: 12px;
  right: 494px;
  bottom: 0;
  color: #9f9f9f;
  font-family: Inter, var(--default-font-family);
  font-size: 6.400000095367432px;
  font-weight: 600;
  line-height: 7.745px;
  text-align: left;
  z-index: 65;
}
.span-dblc-44 {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 11px;
  right: 235px;
  bottom: 1px;
  color: #a9a9a9;
  font-family: Inter, var(--default-font-family);
  font-size: 7.300000190734863px;
  font-weight: 600;
  line-height: 8.835px;
  text-align: left;
  white-space: nowrap;
  z-index: 62;
}
.span-45 {
  display: flex;
  align-items: center;
  justify-content: center;
  position: absolute;
  width: 18px;
  height: 11px;
  right: 158px;
  bottom: 1px;
  color: #999999;
  font-family: Inter, var(--default-font-family);
  font-size: 7.900000095367432px;
  font-weight: 600;
  line-height: 9.561px;
  text-align: center;
  white-space: nowrap;
  z-index: 61;
}
.span-46 {
  display: block;
  position: relative;
  height: 12px;
  margin: -3px 0 0 86px;
  color: #a0a0a0;
  font-family: Inter, var(--default-font-family);
  font-size: 7.300000190734863px;
  font-weight: 600;
  line-height: 8.835px;
  text-align: left;
  white-space: nowrap;
  z-index: 63;
}
.mobile-banking-47 {
  display: block;
  position: relative;
  height: 11px;
  margin: 1px 0 0 86px;
  color: #989898;
  font-family: Inter, var(--default-font-family);
  font-size: 6.800000190734863px;
  font-weight: 600;
  line-height: 8.23px;
  text-align: left;
  white-space: nowrap;
  z-index: 59;
}
.ae-48 {
  display: block;
  position: relative;
  height: 11px;
  margin: 2px 0 0 86px;
  color: #aeaeae;
  font-family: Inter, var(--default-font-family);
  font-size: 7.300000190734863px;
  font-weight: 600;
  line-height: 8.835px;
  text-align: left;
  white-space: nowrap;
  z-index: 58;
}
.manojpudasaini-n {
  display: block;
  position: relative;
  height: 11px;
  margin: 2px 0 0 86px;
  color: #ababab;
  font-family: Inter, var(--default-font-family);
  font-size: 7.199999809265137px;
  font-weight: 600;
  line-height: 8.714px;
  text-align: left;
  white-space: nowrap;
  z-index: 57;
}
.mlc-49 {
  display: block;
  position: relative;
  height: 11px;
  margin: 1px 0 0 86px;
  color: #989898;
  font-family: Inter, var(--default-font-family);
  font-size: 7.300000190734863px;
  font-weight: 600;
  line-height: 8.835px;
  text-align: left;
  white-space: nowrap;
  z-index: 56;
}
.background-4a {
  position: relative;
  width: 547px;
  height: 1px;
  margin: 0 0 0 23px;
  background: #ffffff;
  z-index: 54;
}
.groups-4b {
  position: absolute;
  width: 595px;
  height: 57px;
  right: 0;
  bottom: 230px;
  background: rgba(0, 0, 0, 0);
  z-index: 42;
}
.flex-row-af {
  position: relative;
  width: 544px;
  height: 13px;
  margin: 2px 0 0 26px;
  z-index: 53;
}
.comma {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 12px;
  right: 0;
  bottom: 1px;
  color: #a7a7a7;
  font-family: Inter, var(--default-font-family);
  font-size: 7.199999809265137px;
  font-weight: 600;
  line-height: 8.714px;
  text-align: left;
  white-space: nowrap;
  z-index: 50;
}
.visa-r {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 12px;
  right: 345px;
  bottom: 0;
  color: #979797;
  font-family: Inter, var(--default-font-family);
  font-size: 7.900000095367432px;
  font-weight: 600;
  line-height: 9.561px;
  text-align: left;
  white-space: nowrap;
  z-index: 53;
}
.pe {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 11px;
  right: 237px;
  bottom: 1px;
  color: #ababab;
  font-family: Inter, var(--default-font-family);
  font-size: 7.300000190734863px;
  font-weight: 600;
  line-height: 8.835px;
  text-align: left;
  white-space: nowrap;
  z-index: 52;
}
.dot {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 11px;
  right: 89px;
  bottom: 1px;
  color: #9e9e9e;
  font-family: Inter, var(--default-font-family);
  font-size: 7.800000190734863px;
  font-weight: 600;
  line-height: 9.44px;
  text-align: left;
  white-space: nowrap;
  z-index: 51;
}
.background-4c {
  position: relative;
  width: 546px;
  height: 2px;
  margin: 1px 0 0 24px;
  background: #ffffff;
  z-index: 49;
}
.ramezhypermkta-jm {
  display: block;
  position: relative;
  height: 10px;
  margin: 16px 0 0 86px;
  color: #9f9f9f;
  font-family: Inter, var(--default-font-family);
  font-size: 7.900000095367432px;
  font-weight: 600;
  line-height: 9.561px;
  text-align: left;
  white-space: nowrap;
  z-index: 46;
}
.cash-withdrawal {
  display: block;
  position: relative;
  height: 11px;
  margin: 1px 0 0 86px;
  color: #969696;
  font-family: Inter, var(--default-font-family);
  font-size: 7.300000190734863px;
  font-weight: 600;
  line-height: 8.835px;
  text-align: left;
  white-space: nowrap;
  z-index: 43;
}
.flex-row-db {
  position: absolute;
  width: 484px;
  height: 12px;
  right: 25px;
  bottom: 23px;
  z-index: 47;
}
.atm-cash-withdraw {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 11px;
  right: 233px;
  bottom: 1px;
  color: #a1a1a1;
  font-family: Inter, var(--default-font-family);
  font-size: 7.699999809265137px;
  font-weight: 600;
  line-height: 9.319px;
  text-align: left;
  white-space: nowrap;
  z-index: 47;
}
.comma-4d {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 12px;
  right: 0;
  bottom: 0;
  color: #a3a3a3;
  font-family: Inter, var(--default-font-family);
  font-size: 7.199999809265137px;
  font-weight: 600;
  line-height: 8.714px;
  text-align: left;
  white-space: nowrap;
  z-index: 44;
}
.dot-4e {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 11px;
  right: 160px;
  bottom: 0;
  color: #a3a3a3;
  font-family: Inter, var(--default-font-family);
  font-size: 7.300000190734863px;
  font-weight: 600;
  line-height: 8.835px;
  text-align: left;
  white-space: nowrap;
  z-index: 45;
}
.date-4f {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  width: 46px;
  height: 12px;
  right: 523px;
  bottom: 22px;
  color: #9d9d9d;
  font-family: Inter, var(--default-font-family);
  font-size: 6.400000095367432px;
  font-weight: 600;
  line-height: 7.745px;
  text-align: left;
  z-index: 48;
}
.philly-steakrest {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  width: 156px;
  height: 23px;
  right: 352.333px;
  bottom: 193px;
  color: #a3a3a3;
  font-family: Inter, var(--default-font-family);
  font-size: 7.400000095367432px;
  font-weight: 300;
  line-height: 9.762px;
  text-align: left;
  text-overflow: initial;
  z-index: 37;
  overflow: hidden;
}
.image-50 {
  position: absolute;
  width: 150px;
  height: 111px;
  right: 26px;
  bottom: 42px;
  background: url(./assets/images/9369c26a2676710b2b7de8a54d55d65d56cadaf9.png)
    no-repeat center;
  background-size: cover;
  z-index: 18;
}
.flex-column-a {
  position: relative;
  width: 30px;
  height: 37px;
  margin: 18px 0 0 121px;
  font-size: 0px;
  z-index: 24;
  overflow: visible auto;
}
.percent {
  display: block;
  position: relative;
  height: 11px;
  margin: 0 0 0 0;
  color: #a4a4a4;
  font-family: Inter, var(--default-font-family);
  font-size: 9px;
  font-weight: 600;
  line-height: 10.892px;
  text-align: left;
  white-space: nowrap;
  z-index: 24;
}
.dot-51 {
  display: block;
  position: relative;
  height: 11px;
  margin: 15px 0 0 2px;
  color: #a2a2a2;
  font-family: Inter, var(--default-font-family);
  font-size: 7.900000095367432px;
  font-weight: 600;
  line-height: 9.561px;
  text-align: left;
  white-space: nowrap;
  z-index: 21;
}
.image-52 {
  position: relative;
  width: 9px;
  height: 10px;
  margin: -1px 0 0 32px;
  background: url(./assets/images/698b67fa2ffbf24c0cd1b44dcfbb7a1afadb28b1.png)
    no-repeat center;
  background-size: cover;
  z-index: 22;
}
.image-53 {
  position: relative;
  width: 9px;
  height: 9px;
  margin: 10px 0 0 20px;
  background: url(./assets/images/b5e538692f44089504ca196a38b9940e7e4dd9f8.png)
    no-repeat center;
  background-size: cover;
  z-index: 20;
}
.ashred {
  display: block;
  position: relative;
  height: 14px;
  margin: 5px 0 0 37px;
  color: #6c9de4;
  font-family: Inter, var(--default-font-family);
  font-size: 13.5px;
  font-weight: 400;
  line-height: 14px;
  text-align: left;
  white-space: nowrap;
  z-index: 19;
}
.groups-54 {
  position: absolute;
  width: 595px;
  height: 37px;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0);
  z-index: 141;
}
.page-of {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 14px;
  right: 257px;
  bottom: 18px;
  color: #8f8f8f;
  font-family: Inter, var(--default-font-family);
  font-size: 9.100000381469727px;
  font-weight: 600;
  line-height: 11.013px;
  text-align: left;
  white-space: nowrap;
  z-index: 142;
}
.background-55 {
  position: absolute;
  width: 595px;
  height: 841px;
  right: 0;
  bottom: 0;
  background: url(./assets/images/531060a9a1bbc629927166e002f48c788161005d.png)
    no-repeat center;
  background-size: cover;
  z-index: 2;
}

    </style>
  </head>
  <body>
    <div class="main-container">
      <div class="root">
        <div class="groups">
          <div class="image"></div>
          <div class="flex-row-b">
            <div class="image-1"></div>
            <div class="background"></div>
            <span class="mashreq">mashreq</span
            ><span class="al-mashreq">المشرق</span>
            <div class="image-2"></div>
            <span class="ned">NED</span><span class="aldlam">ALDLAM9</span>
            <div class="groups-3">
              <span class="kashf-hisab-al-jari">كشف حساب الجاري</span
              ><span class="current-account-statement"
                >Current account statement</span
              ><span class="islamic-banking">ISLAMIC BANKING</span>
              <div class="background-4"></div>
              <span class="raqm-al-hisab">رقم الحساب</span>
              <div class="flex-row-d">
                <span class="account-number">019120159118</span
                ><span class="aed">AED</span>
              </div>
              <span class="account-number-5">Account Number</span
              ><span class="manoj-pudasaini">MANOJPUDASAINI</span>
              <div class="background-6"></div>
              <span class="aban">ابان</span>
              <div class="flex-row-abb">
                <span class="iban">IBAN</span
                ><span class="ae">AE870330000019120159118</span>
              </div>
              <div class="flex-row">
                <span class="alkuwait-street">AlKuwait Street aghaadir Building 1st floor Al Mas</span>
                <div class="background-7"></div>
              </div>
              <span class="rafm-taresh-al-amel">رفم تعرش العميل</span
              ><span class="customer">Customer</span
              ><span class="phone-number">015011111</span
              ><span class="address">AlMankhool-Dubai-United ArabEmirates</span>
              <div class="background-8"></div>
              <div class="flex-row-eb">
                <span class="location">Dubai</span>
                <div class="image-9"></div>
              </div>
              <div class="image-a"></div>
              <span class="country-code">AE</span
              ><span class="greeting">Dear Customer.</span
              ><span class="compliance-message"
                >Mashreq including its domestic and foreign branches, is
                committed and keen on ensuring ful compliance with allapplicable
                laws, regulations and sanction<br />requirements and would lke
                to remind its customers of the restrictions that the bank has in
                place on customer activity related to sanctioned countries<br />Kindy
                visit mashreq.com/sanctions for further detals.</span
              >
              <div class="flex-row-e">
                <span class="statement-period">Statement for period</span
                ><button class="button">2024-10-16</button
                ><span class="date">2024-04-01</span><span class="to">to</span>
              </div>
              <div class="background-b"></div>
              <div class="flex-row-e-c">
                <span class="debit">Debit</span
                ><span class="credit">Credit</span
                ><span class="balance">Balance</span
                ><span class="transaction">Transaction<br />المعاملة</span
                ><span class="reference-number">Reference No</span
                ><span class="date-d">التاريخ</span
                ><span class="amount">قبور</span
                ><span class="balance-amount">الرصيد</span>
              </div>
              <span class="remaining-balance">قبور رالنه</span
              ><span class="reference-number-e">eرفم المرج</span>
            </div>
            <span class="amount-f">13,025.53</span
            ><span class="opening-balance">Opening Balance</span>
            <div class="background-10"></div>
            <span class="transaction-details"
              >VisaPurchase-2590330957576QHI</span
            ><span class="span">1,375.63</span
            ><span class="span-11">2024-04-01</span
            ><span class="span-12">030POS8240921GPz</span
            ><span class="span-13">26.00</span>
            <div class="div"></div>
            <span class="span-14">VisaPurchase-259 0330054485UBFLY1</span
            ><span class="span-15">963.18</span
            ><span class="span-16">2024-04-01</span
            ><span class="span-17">030PO58240921042</span
            ><span class="span-18">412.45</span
            ><span class="span-19">AED ISTANBULAED407.36 0330</span>
            <div class="div-1a"></div>
            <span class="span-1b">VisaPurchase-2590331326603 CITTAX</span
            ><span class="span-1c">33.00</span
            ><span class="span-1d">930.18</span
            ><span class="span-1e">2024-04-01</span
            ><span class="span-1f">030POSB240921PQK</span
            ><span class="span-20">AED ShaRJAh AE AED 33 0331</span
            ><span class="span-21">VisaPurchase-2590331328294BUYN</span
            ><span class="span-22">25.22</span
            ><span class="span-23">2024-04-01</span
            ><span class="span-24">030POSB240921QWt</span
            ><span class="span-25">SaVE AEd AJman aE AEd 25.22 0331</span>
            <div class="div-26"></div>
            <span class="span-27">VisaPurchase-2590331252785BUYN</span
            ><span class="span-28">2024-04-01</span
            ><span class="span-29">030POSB240921Sas</span
            ><span class="span-2a">33.99</span
            ><span class="span-2b">SAVE AEDAJMANAEAED 33.990331</span>
          </div>
          <div class="div-2c">
            <div class="div-2d"></div>
            <span class="span-2e">Value AddedTax-Output-TOC-MAE-</span>
            <div class="flex-row-a">
              <span class="span-2f">13,025.48</span
              ><span class="span-30">2024-03-30</span
              ><span class="span-dblc">033DBLC240903362</span
              ><span class="span-31">0.05</span>
            </div>
            <span class="span-32">01501111-240331024759FUNDTRANSFER-</span
            ><span class="mobile-banking">MOBILE BANKING</span
            ><span class="span-ae">/AE180400000193308926001</span
            ><span class="span-33">MANOJ PUDASAINI NRAKAEAKXXX SRN:</span
            ><span class="mlc">MLC31032491418</span>
          </div>
          <div class="groups-34">
            <div class="background-35"></div>
            <span class="online-local-fund"
              >Online Local Fund Transfer-TOC-MAE-</span
            >
            <div class="flex-row-eb-36">
              <span class="span-37">1,025.48</span
              ><span class="span-38">2024-03-30</span
              ><span class="span-dblc-39">033DBLC240903362</span
              ><span class="span-3a">12,000.00</span>
            </div>
            <span class="span-3b">01501111-240331024759FUNDTRANSFER-</span
            ><span class="mobile-banking-3c">MOBILE BANKING</span
            ><span class="span-ae-3d">/AE180400000193308926001</span
            ><span class="span-3e">MANOJ PUDASAININRAKAEAKXXX SRN:</span
            ><span class="mlc-3f">MLC31032491418</span>
          </div>
          <div class="groups-40">
            <div class="background-41"></div>
            <span class="funds-transfer-c"
              >Funds Transfer Charges-TOC-MAE-</span
            >
            <div class="flex-row-ac">
              <span class="span-42">1,024.48</span
              ><span class="span-43">2024-03-30</span
              ><span class="span-dblc-44">033DBLC240903362</span
              ><span class="span-45">1.00</span>
            </div>
            <span class="span-46">01501111-240331024759FUNDTRANSFER-</span
            ><span class="mobile-banking-47">MOBILE BANKING</span
            ><span class="ae-48">/AE180400000193308926001</span
            ><span class="manojpudasaini-n"
              >MANOJPUDASAINI NRAKAEAKXXX SRN:</span
            ><span class="mlc-49">MLC31032491418</span>
            <div class="background-4a"></div>
          </div>
          <div class="groups-4b">
            <div class="flex-row-af">
              <span class="comma">1,601.63</span
              ><span class="visa-r"
                >2024-03-30 VisaRefund-662251701TURNA.COM</span
              ><span class="pe">030PE31240922597</span
              ><span class="dot">577.15</span>
            </div>
            <div class="background-4c"></div>
            <span class="ramezhypermkta-jm">RAMEZHYPERMKTAJMANAEAEDATM</span
            ><span class="cash-withdrawal">CASHWTHDRAWAL31-MAR-24195839</span>
            <div class="flex-row-db">
              <span class="atm-cash-withdraw"
                >ATM CashWithdrawal-SDU00327840032-038vCAW2409202SG</span
              ><span class="comma-4d">1,401.63</span
              ><span class="dot-4e">200.00</span>
            </div>
            <span class="date-4f">2024-03-31</span>
          </div>
          <span class="philly-steakrest"
            >PHILLY STEAKREST AED SHARJAH AED 26<br />0330</span
          >
          <div class="image-50">
            <div class="flex-column-a">
              <span class="percent">904.%</span
              ><span class="dot-51">870.97</span>
            </div>
          </div>
          <div class="groups-54"><span class="page-of">Page1 of26</span></div>
        </div>
      </div>
      <div class="background-55"></div>
    </div>
  </body>
</html>
